[tool.poetry]
name = "universal-playlists"
version = "0.1.0"
description = ""
authors = ["platers <platers81@gmail.com>"]

[tool.poetry.scripts]
universal-playlists = "universal_playlists.cli.cli:app"
up-data= "universal_playlists.eval.data.create_dataset:main"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.4.1"}
pandas = "^1.4.2"
spotipy = "^2.19.0"
ytmusicapi = "^0.21.0"
musicbrainzngs = "^0.7.1"
pydantic = "^1.9.0"
strsimpy = "^0.2.1"
rich = "^12.2.0"
ratelimit = "^2.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
tqdm = "^4.64.0"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
