name: PyTest
on: push

jobs:
  test:
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        os: ["linux", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
